before: [.before.coffee]
require:
  - fierry.generation
  - fierry.performance
namespace:
  core:   core
  math:   math
  string: string
  gen:    core.generation

  test:   performance.register_test
  group:  performance.register_group
