before: [.before.coffee]
require:
  - fierry.storage
namespace:
  core:   core
  dao:    core.dao
  pkg:    performance.storage
  test:   performance.register_test
  group:  performance.register_group
