before:
  - .before.coffee
require:
  - fierry.storage
namespace:
  core:    core
  dao:     core.dao
  storage: core.storage
  gen:     core.generation

  pkg:     performance.storage
  test:    performance.register_test
  group:   performance.register_group
  repeat: performance.register_tests_from
  env:     performance.register_environment
