before: [.before.coffee]
require:
  - fierry.generation
  - fierry.performance
namespace:
  core:   core
  array:  array
  gen:    core.generation

  pkg:    performance.array
  test:   performance.registerTest
  group:  performance.registerGroup
