before: [.before.coffee]
require:
  - fierry.core
  - fierry.generation
  - fierry.performance

namespace:
  uid:    uid
  core:   core
  object: object
  gen:    core.generation

  test:   performance.register_test
  group:  performance.register_group
