before: 
  - .before.coffee
  - Create.before.coffee
  - Dom.before.coffee
require:
  - fierry.view
  - fierry.dom
namespace:
  uid:      uid
  core:     core
  assert:   assert

  dom:      core.dom
  view:     core.view

  pkg:      performance.view
  test:     performance.register_test
  group:    performance.register_group

