#
# Module providing core functionality for the Fierry Framework.
# When editing this package keep in mind that most of its
# functionalities won't be accessible from anywhere but
# .after.coffee file.
#
before: 
  - .before.coffee
  - Assert.coffee
after:
  - .after.coffee

namespace:
  core: core
