before:
  - NotifyPoint.coffee
  - PlainDao.coffee
after:
  - .after.coffee
require:
  - fierry.core
  - fierry.async
namespace:
  # Core
  core:     core
  array:    array
  object:   object

  # Helpers
  app:      app
  uid:      uid
  assert:   assert

  # Internal namespaces
  dao:      core.dao
  pkg:      core.storage
  storage:  core.storage

  behavior: app.add_behavior
