after: [.after.coffee]
require:
  - fierry.core
  - fierry.scheduler
namespace:
  # Core
  core:    core
  array:   array
  object:  object

  # Helpers
  app:     core.app
  uid:     core.uid
  assert:  core.assert
  
  # Internal namespaces
  dao:     core.dao
  pkg:     core.storage
  storage: core.storage
