before: [.before.coffee]
require:
  - fierry.core
  - fierry.performance
namespace:
  uid:    uid
  core:   core
  lang:   lang
  math:   math
  array:  array
  assert: assert

  test:   performance.register_test
  group:  performance.register_group
