after:
  - .after.coffee
require:
  - fierry.core
  - fierry.async

namespace:
  app:     app
  core:    core
  math:    math
  array:   array
  string:  string
  assert:  assert

  pfc:     performance
  pkg:     performance.internal
  union:   set.union

  scheduler: core.scheduler.RAW
