after:
  - .after.coffee
require:
  - fierry.core
  - fierry.scheduler

namespace:
  core:    core
  array:   array
  string:  string

  app:     core.app
  assert:  core.assert
  pfc:     performance
  pkg:     performance.internal
  union:   set.union

  scheduler: core.scheduler.RAW
