before: [.before.coffee]
require:
  - fierry.generation
  - fierry.performance
namespace:
  core:  core
  gen:   core.generation

  pkg:   performance.string
  test:  performance.registerTest
  group: performance.registerGroup
